#!/usr/bin/env bash
# patch-propolis.sh — Download and install patched propolis-server binary
# Generated by the build-release workflow. RELEASE_TAG is baked in at build time.
set -euo pipefail

RELEASE_TAG="__RELEASE_TAG__"
REPO="swherdman/propolis"
BINARY_URL="https://github.com/${REPO}/releases/download/${RELEASE_TAG}/propolis-server.gz"

echo "=== Propolis String I/O Patch Installer ==="
echo "Release: ${RELEASE_TAG}"
echo ""

# Detect tarball location
if [ -f "$HOME/omicron/out/propolis-server.tar.gz" ]; then
    TARBALL="$HOME/omicron/out/propolis-server.tar.gz"
    echo "Found: ${TARBALL} (fresh deploy)"
elif [ -f "/opt/oxide/propolis-server.tar.gz" ]; then
    TARBALL="/opt/oxide/propolis-server.tar.gz"
    echo "Found: ${TARBALL} (existing deployment)"
else
    echo "ERROR: No propolis-server.tar.gz found in ~/omicron/out/ or /opt/oxide/"
    echo "Run omicron-package package first, or specify the path:"
    echo "  TARBALL=/path/to/propolis-server.tar.gz bash patch-propolis.sh"
    exit 1
fi

# Allow override
TARBALL="${TARBALL:-}"

# Download
echo "Downloading patched binary..."
curl -fL "${BINARY_URL}" | gunzip > /tmp/propolis-server
chmod +x /tmp/propolis-server
echo "Downloaded: $(ls -lh /tmp/propolis-server | awk '{print $5}')"

# Repack tarball
echo "Repacking tarball..."
REPACK_DIR=$(mktemp -d /tmp/propolis-repack.XXXXXX)
cd "${REPACK_DIR}"
tar xzf "${TARBALL}"
cp /tmp/propolis-server root/opt/oxide/propolis-server/bin/propolis-server

if [ "${TARBALL}" = "/opt/oxide/propolis-server.tar.gz" ]; then
    pfexec tar czf "${TARBALL}" oxide.json root/
else
    tar czf "${TARBALL}" oxide.json root/
fi

# Clean up
rm -rf "${REPACK_DIR}" /tmp/propolis-server

echo ""
echo "Patched: ${TARBALL}"
echo ""
if [ "${TARBALL}" = "/opt/oxide/propolis-server.tar.gz" ]; then
    echo "Existing deployment patched. To apply:"
    echo "  cd ~/omicron"
    echo "  pfexec ./target/release/omicron-package uninstall"
    echo "  pfexec ./target/release/omicron-package install"
    echo "  # Wait 5-8 min for zones to come back"
else
    echo "Tarball patched. Continue with:"
    echo "  cd ~/omicron && pfexec ./target/release/omicron-package install"
fi
